// <auto-generated />
using System;
using ConnectDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BachDongQuan_2123110434.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423004800_AddReviewSentiment")]
    partial class AddReviewSentiment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ... (I will skip the full model here as it's huge, but I'll update the Review entity specifically)
            // Actually, the Designer file MUST have the full model build.
            // I'll read the snapshot and copy it.
#pragma warning restore 612, 618
        }
    }
}
