name: Deploy Backend to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'BachDongQuan_2123110434/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t cinema-backend ./BachDongQuan_2123110434

      # Render auto-deploys when we push to GitHub if hooked up correctly.
      # This workflow is mainly for Testing and keeping track of builds.
      - name: Notify Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
